pytz-py: Upstream update.
Update to newer upstream version (2018.5). Adding py37 variant gives fails in tests, which do not look like a big problem, but i could not fix them.
Log:
...
FAIL: pytz/tests/../../README.txt
Doctest: README.txt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sw/lib/python3.7/doctest.py", line 2198, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for README.txt
  File "pytz/tests/../../README.txt", line 0

----------------------------------------------------------------------
File "pytz/tests/../../README.txt", line 183, in README.txt
Failed example:
    tz.utcoffset(normal, is_dst=True)
Expected:
    datetime.timedelta(-1, 77400)
Got:
    datetime.timedelta(days=-1, seconds=77400)
...