zmq-py: enable test sources for python3, update to 17.1.3
The tests fail with:

ImportError: cannot import name 'constants'

I found that in buildutils, but no idea, how to tell python the location.