pv-py: partial step towards working TestScript
The TestScript fails with:

ModuleNotFoundError: No module named 'htmlentitydefs'

'htmlentitydefs' is outdated and removed from newer python.